# Generated by Django 2.2.10 on 2020-02-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('portfolios', '0001_initial'),
        ('accouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tech_category',
            field=models.ManyToManyField(blank=True, related_name='user_category', to='portfolios.Tech'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
