# Generated by Django 2.2.10 on 2020-02-18 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('region', models.TextField()),
                ('qualitification', models.TextField()),
                ('content', models.TextField()),
                ('population', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('company_url', models.TextField()),
                ('recruit_logo', models.TextField(blank=True)),
                ('applicant_competition_user', models.ManyToManyField(blank=True, related_name='applicant_competition_company', to=settings.AUTH_USER_MODEL)),
                ('tech_category', models.ManyToManyField(blank=True, related_name='competiton_category', to='portfolios.Tech')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
