# Generated by Django 2.2.10 on 2020-02-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='company_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='population',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='qualitificatioin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='region',
            field=models.TextField(blank=True),
        ),
    ]
