# Generated by Django 2.2.10 on 2020-02-18 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('public', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('project_start', models.DateField(auto_now=True)),
                ('project_end', models.DateField(auto_now=True)),
                ('content_img_1', models.TextField(blank=True)),
                ('content_sub_1', models.TextField(blank=True)),
                ('content_img_2', models.TextField(blank=True)),
                ('content_sub_2', models.TextField(blank=True)),
                ('content_img_3', models.TextField(blank=True)),
                ('content_sub_3', models.TextField(blank=True)),
                ('content_img_4', models.TextField(blank=True)),
                ('content_sub_4', models.TextField(blank=True)),
                ('content_img_5', models.TextField(blank=True)),
                ('content_sub_5', models.TextField(blank=True)),
                ('content_img_6', models.TextField(blank=True)),
                ('content_sub_6', models.TextField(blank=True)),
                ('content_img_7', models.TextField(blank=True)),
                ('content_sub_7', models.TextField(blank=True)),
                ('content_img_8', models.TextField(blank=True)),
                ('content_sub_8', models.TextField(blank=True)),
                ('content_img_9', models.TextField(blank=True)),
                ('content_sub_9', models.TextField(blank=True)),
                ('content_img_10', models.TextField(blank=True)),
                ('content_sub_10', models.TextField(blank=True)),
                ('tech_category', models.ManyToManyField(blank=True, related_name='portfolio_category', to='portfolios.Tech')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
