# Generated by Django 2.2.10 on 2020-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
